[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV          = "production"
  DATABASE_URL      = "$NEON_DATABASE_URL"
  JWT_SECRET        = "$JWT_SECRET"
  VITE_API_BASE_URL = "/.netlify/functions"

[dev]
  command        = "npm run dev"
  port           = 8888
  targetPort     = 5173
  functions      = "netlify/functions"
  environment = { NODE_ENV="development", DATABASE_URL="$NEON_DATABASE_URL", JWT_SECRET="$JWT_SECRET", VITE_API_BASE_URL="/.netlify/functions" }

[functions]
  directory     = "netlify/functions"
  node_bundler  = "esbuild"

[[redirects]]
  from      = "/*"
  to        = "/index.html"
  status    = 200
  force     = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options            = "DENY"
    X-XSS-Protection           = "1; mode=block"
    X-Content-Type-Options     = "nosniff"
    Referrer-Policy            = "strict-origin-when-cross-origin"
    Strict-Transport-Security  = "max-age=31536000; includeSubDomains; preload"